# Unicode symbols for emojis can be found at https://getsymbols.com/
format = """
$directory $git_branch $git_state $cmake
[🎄](bold white) """

[directory]
truncation_length = 3
truncate_to_repo  = false
truncation_symbol = "../"
format = "[$path](bold cyan)[$read_only]($read_only_style)"

[git_branch]
format = "|[$branch](bold purple)|"

[cmake]
disabled = true